language: node_js
node_js: 14
branches:
  only: master
install:
  - rm -rf ./.yarn/cache/
  - rm -rf ./.yarn/sdks/
  - rm -rf ./.yarn/unplugged/
  - rm -rf ./.yarn/build-state.yml
  - rm -rf ./.yarn/install-state.gz
  - yarn
script:
  - yarn build
  - yarn test
deploy:
  api_key:
    secure: Nkjnerv6RM1DfEdh6iSOhIus3VEATUZoPE6FUIS6PMzsxv4QklLOv3ovjrHZp6yTG90nmutZ7G1DWXHFVGtK6yFVH2gYHGNxYAi+eyL/gUJqVXwwrOLTpNLiyo0YqKUstsFitCjlZOCycacMBe7ALt+3BZkYHDQwW7gRgNRZbVfZbfIjCAnEEsvtF0TtwXUJOd7MKj1hluCGb9rbWupvrOAXEGA8JfjZ9Xnvj/Xm+G3m25fBhg61ZFhSlfeuBFtteWas2KcODAt1aPCm0kJ/5i8upD3mZDBoOpNIJ8S+TnSnMheksUEPZiodftb0Yb2mKxK9ZLMRfDazlQXaTq20k1dPHwRtsJhDH1q5wATFBjBuOZ5dwhModpFeDQfiGhv7ZVVMMcrfuziuhYjAKoQiog6ZTBhIzJrfYr7UQ8rfrPqMAjGKH9EWCNnL66gms0zidABdwIQYHk9eSeSxO2iTB/o9y7sDMlKPB9d7QCUedb10B2kBmoDBGHA3o8MRBx/WQM2SOn0d5TaAmEq3Ld6i+djcOVqgOGO/sSI9X5TJhzfNUrBDmDFLIg2dLu21PcyZl5oZ8nn0cC1ZuIwM7IRq6l+UZEZ2F537mRnouOmaniHHc9IL16qPteSU7WKD+r9BMB73PmjfMGTTyDRwLVgpv0rvbkVBjzRKnL01pAqNX2o=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
